[project]
name = "park-up-edge-node"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
<<<<<<< HEAD
    "fastapi>=0.115.12",
=======
    "accelerate>=1.7.0",
    "easyocr>=1.7.2",
    "einops>=0.8.1",
    "fastapi>=0.115.12",
    "numpy>=2.3.0",
    "safetensors>=0.5.3",
    "torch>=2.7.1",
    "transformers>=4.52.4",
>>>>>>> df826e83454f69e7f786f6480bdf8d77da63a022
    "uvicorn>=0.34.3",
]
